# Generated by Django 2.2.16 on 2022-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220708_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Новый пост', max_length=200, verbose_name='Заголовок'),
        ),
    ]
