# Generated by Django 4.0.6 on 2022-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Новый пост', max_length=200, verbose_name='Название поста'),
        ),
    ]
