# Generated by Django 4.0.6 on 2022-07-15 10:38

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('posts', '0006_alter_post_tags_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите теги', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
