# Generated by Django 4.0.6 on 2022-07-25 11:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('posts', '0008_rutag_rutaggeditem_alter_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='posts.RuTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
